/**
 * DB mapping helpers — alpha_transactions (snake_case) ↔ Transaction (camelCase)
 */

import type { Transaction, TransactionInput } from "./types"

// ── DB ROW TYPE (matches alpha_transactions columns) ──────────────────────────

export interface AlphaTransactionRow {
  id: string
  uid: string
  client_reference: string
  client_user_id: string | null
  iso_timestamp: string
  pol: string
  pod: string
  incoterm: string
  value_fob: number | string
  alpha_commission: number | string
  total_value: number | string
  deposit60: number | string
  balance40: number | string
  currency: string
  deposit_status: string
  balance_status: string
  current_step: string
  responsible_agent: string
  tracking_number: string
  priority: string
  incident_log: string
  client_visible: boolean
  created_at: string
  updated_at: string
}

/** Convert a DB row to a Transaction object (camelCase). */
export function rowToTransaction(row: AlphaTransactionRow): Transaction {
  return {
    uid:              row.uid,
    clientReference:  row.client_reference,
    isoTimestamp:     row.iso_timestamp,
    pol:              row.pol,
    pod:              row.pod,
    incoterm:         row.incoterm as Transaction["incoterm"],
    valueFOB:         Number(row.value_fob),
    alphaCommission:  Number(row.alpha_commission),
    totalValue:       Number(row.total_value),
    deposit60:        Number(row.deposit60),
    balance40:        Number(row.balance40),
    currency:         row.currency as Transaction["currency"],
    depositStatus:    row.deposit_status as Transaction["depositStatus"],
    balanceStatus:    row.balance_status as Transaction["balanceStatus"],
    currentStep:      row.current_step as Transaction["currentStep"],
    responsibleAgent: row.responsible_agent,
    trackingNumber:   row.tracking_number,
    priority:         row.priority as Transaction["priority"],
    incidentLog:      row.incident_log,
    clientVisible:    row.client_visible,
  }
}

/** Convert a Transaction (camelCase) to DB insert/update shape (snake_case).
 *  Accepts the full validated schema input — computed fields (totalValue,
 *  deposit60, balance40) are silently ignored as they are generated by the DB.
 */
export function transactionToRow(
  tx: TransactionInput | Omit<Transaction, "totalValue" | "deposit60" | "balance40">,
  clientUserId?: string | null,
): Omit<AlphaTransactionRow, "id" | "total_value" | "deposit60" | "balance40" | "created_at" | "updated_at"> {
  return {
    uid:              tx.uid,
    client_reference: tx.clientReference,
    client_user_id:   clientUserId ?? null,
    iso_timestamp:    tx.isoTimestamp,
    pol:              tx.pol,
    pod:              tx.pod,
    incoterm:         tx.incoterm,
    value_fob:        tx.valueFOB,
    alpha_commission: tx.alphaCommission,
    currency:         tx.currency,
    deposit_status:   tx.depositStatus,
    balance_status:   tx.balanceStatus,
    current_step:     tx.currentStep,
    responsible_agent: tx.responsibleAgent,
    tracking_number:  tx.trackingNumber,
    priority:         tx.priority,
    incident_log:     tx.incidentLog,
    client_visible:   tx.clientVisible,
  }
}
